PROPERTY_TO_ANALYSIS = {
    "bogus": "AcklandJonesModifier",
    "AcklandJones_counts_OTHER": "AcklandJonesModifier",
    "AcklandJones_counts_FCC": "AcklandJonesModifier",
    "AcklandJones_counts_HCP": "AcklandJonesModifier",
    "AcklandJones_counts_BCC": "AcklandJonesModifier",
    "CommonNeighborAnalysis_counts_FCC": "CommonNeighborAnalysisModifier",
    "CommonNeighborAnalysis_counts_HCP": "CommonNeighborAnalysisModifier",
    "CommonNeighborAnalysis_counts_BCC": "CommonNeighborAnalysisModifier",
    "CommonNeighborAnalysis_counts_ICO": "CommonNeighborAnalysisModifier",
    "CommonNeighborAnalysis_counts_OTHER": "CommonNeighborAnalysisModifier",
    "PolyhedralTemplateMatching_counts_OTHER": "PolyhedralTemplateMatchingModifier",
    "PolyhedralTemplateMatching_counts_FCC": "PolyhedralTemplateMatchingModifier",
    "PolyhedralTemplateMatching_counts_HCP": "PolyhedralTemplateMatchingModifier",
    "PolyhedralTemplateMatching_counts_BCC": "PolyhedralTemplateMatchingModifier",
}
